# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: frontend
#   namespace: expense
# data:
#   DB_HOST: mysql # mysql component service name
---
apiVersion: webs/v1
kind: Deployment
metadata:
  name: frontend
  namespace: expense
  labels:
    component: frontend
    project: expense
    tier: web
spec:
  replicas: 2
  selector:
    matchLabels:
      component: frontend
      project: expense
      tier: web
  template:
    metadata: # corrected the spelling here
      labels:
        component: frontend # changed to match the selector labels
        project: expense
        tier: web
    spec: 
      containers:
      - name: frontend
        image: joindevops/frontend:v1.0
        # envFrom:
        # - configMapRef:
        #     name: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: expense
  labels:
    name: frontend
    project: expense
    component: frontend # fixed spelling here
    environment: dev
spec:
  type: LoadBalancer
  selector: # added selector for correct routing
    component: frontend
  ports:
  - protocol: TCP
    port: 80 # load balancer port
    targetPort: 80 # target container port
    