apiVersion: v1
kind: ConfigMap
metadata:
  name: backend
  namespace: expense
data:
  DB_HOST: mysql # mysql component service name
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  labels:
    component: backend
    project: expense
    tier: app
spec:
  replicas: 2
  selector:
    matchLabels:
      component: backend
      project: expense
      tier: app
  template:
    metadata: # corrected the spelling here
      labels:
        component: backend # changed to match the selector labels
        project: expense
        tier: app
    spec: 
      containers:
      - name: backend
        image: joindevops/backend:v1.0
        envFrom:
        - configMapRef:
            name: backend
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: expense
  labels:
    name: backend
    project: expense
    component: backend # fixed spelling here
    environment: dev
spec:
  selector: # added selector for correct routing
    component: backend
  ports:
  - protocol: TCP
    port: 8080 # load balancer port
    targetPort: 8080 # target container port
    

    



