apiVersion: v1
kind: Deployment
metadata:
  name: mysql
  namespace: expense
  #this labels are related to dployment
  labels:
    component: mysql
    project: Expense
    tier: database
  spec:
    replicas: 3
    selector:
      matchLabels:
        component: mysql
        project: Expense
        tier: database
    templet: 
      metadate:
        lables:
          component: mysql
          project: Expense
          tier: database
      spec: 
        containers:
          - name: mysql
            image: joindevops/mysql:v1.0
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: expense
spec:
  selector:
     component: mysql
     project: Expense
     tier: database
ports:
- protocol: TCP
  port: 3306 #load balancer
  targetport: 3306 #target port
  
    

    



