apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: expense
  #this labels are related to dployment
  labels:
    component: mysql
    project: expense
    tier: database
  spec:
    replicas: 3
    selector:
      matchLabels:
        component: mysql
        project: expense
        tier: database
    template: 
      metadate:
        lables:
          component: mysql
          project: expense
          tier: database
      spec: 
        containers:
          - name: mysql
            image: joindevops/mysql:v1.0

    

    



